/// `check-script init` : génère un `.checkscript.yaml` commenté, avec un
/// profil suggéré d'après l'analyse des scripts du dossier.
library;

import 'config.dart';
import 'i18n.dart';
import 'model/report.dart';
import 'rules/catalog.dart' show ExecContext;
import 'version.dart';

/// Nom par défaut du rapport de référence écrit par `init --baseline`.
const defaultBaselineName = '.checkscript-baseline.json';

/// Profil suggéré d'après les notes des scripts : `strict` pour du code déjà
/// propre (moyenne ≥ 8,5), `legacy` pour du code ancien à la peine (moyenne
/// < 6), `standard` sinon (ou sans script).
Profile suggestProfile(List<ScriptReport> reports) {
  if (reports.isEmpty) return Profile.standard;
  final avg = reports.fold<double>(0, (s, r) => s + r.global) / reports.length;
  if (avg >= 8.5) return Profile.strict;
  if (avg < 6) return Profile.legacy;
  return Profile.standard;
}

/// Note moyenne des [reports] (0 si vide).
double averageScore(List<ScriptReport> reports) => reports.isEmpty
    ? 0
    : reports.fold<double>(0, (s, r) => s + r.global) / reports.length;

/// Contenu du `.checkscript.yaml` généré. [note] : phrase expliquant le
/// choix du profil (commentaire en tête). Seules les clés `profile`,
/// `context` et `exclude` sont actives ; le reste est un exemple commenté.
String renderInitConfig(
    {required Profile profile,
    Set<ExecContext> contexts = const {},
    List<String> exclude = const [],
    required Lang lang,
    String? note}) {
  String t(String fr, String en) => lang == Lang.fr ? fr : en;
  String list(Iterable<String> v) => '[${v.map((e) => "'$e'").join(', ')}]';
  final name = profile == Profile.standard ? 'default' : profile.name;
  final b = StringBuffer()
    ..writeln(t(
        '# Configuration check-script (générée par `check-script init`, '
            'version $appVersion).',
        '# check-script configuration (generated by `check-script init`, '
            'version $appVersion).'))
    ..writeln(t(
        '# Toutes les clés sont facultatives ; une clé absente garde la '
            'valeur du profil.',
        '# All keys are optional; a missing key keeps the profile\'s value.'))
    ..writeln(t('# Exemple complet commenté : doc/checkscript.example.yaml',
        '# Complete commented example: doc/checkscript.example.yaml'));
  if (note != null) b.writeln('# $note');
  b
    ..writeln()
    ..writeln(t(
        '# Profil de notation : strict (nouveaux scripts) | default | legacy (code ancien).',
        '# Scoring profile: strict (new scripts) | default | legacy (old code).'))
    ..writeln('profile: $name')
    ..writeln()
    ..writeln(t('# Comment les scripts sont lancés : durcit certaines règles.',
        '# How the scripts are run: hardens some rules.'));
  if (contexts.isEmpty) {
    b.writeln('# context: [root, cron, systemd]');
  } else {
    b.writeln('context: ${list([for (final c in contexts) c.name])}');
  }
  b
    ..writeln()
    ..writeln(t(
        '# Chemins ignorés dans un dossier (syntaxe .gitignore). Un fichier '
            '.checkscriptignore à la racine du dossier\n# est lu aussi.',
        '# Paths ignored in a folder (.gitignore syntax). A .checkscriptignore '
            'file at the root of the folder\n# is read too.'));
  if (exclude.isEmpty) {
    b.writeln("# exclude: ['vendor/', 'generated/**', '*.min.sh']");
  } else {
    b.writeln('exclude: ${list(exclude)}');
  }
  b
    ..writeln()
    ..writeln(t('# Règles ignorées, tout outil confondu.',
        '# Rules ignored, whatever the tool.'))
    ..writeln('# rules:')
    ..writeln('#   disabled: [MNT005, SC2034]')
    ..writeln()
    ..writeln(t('# Outils : désactiver ou régler un outil.',
        '# Tools: disable or tune a tool.'))
    ..writeln('# tools:')
    ..writeln('#   semgrep: false              '
        '${t('# machine sans accès réseau', '# machine without network access')}')
    ..writeln('#   shellcheck:')
    ..writeln('#     exclude: [SC1091]')
    ..writeln()
    ..writeln(t('# Version minimale de Python à supporter (entre guillemets).',
        '# Minimum Python version to support (quoted).'))
    ..writeln('# pythonTarget: "${CheckConfig.defaultPythonTarget}"');
  return b.toString();
}
